name: Build Docker Image

on:
  push:

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Login to Docker
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/discord-cloud-storage --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x .

    - name: Push image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/discord-cloud-storage