name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [19.0.0, 19.x, 20.x, 21.x, 22.x, 23.x, 24.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Setup Node
      uses: actions/setup-node@v4.4.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install packages
      run: npm ci

    - name: Transpile TS -> JS
      run: npx tsc

    - name: Run Tests
      run: npm test